@startuml
'https://plantuml.com/class-diagram'


Personer "1..*"-left- "1" Database
TA "0..*"--"0..*" Studerende
Ansatte <|-- TA
Ansatte <|-- Undervisere
Personer <|-- Ansatte
Personer <|-- Studerende
Ansatte <|-- Sekretære
Undervisningsafdeling "1..*" o-- "1..*" Ansatte
Universiteter "1" *-up- "1..*" Undervisningsafdeling
Universiteter "1..2" -- "1..*" Personer

Studerende "1..*"-down-"1" Skema

Skema "1..*"--"1..*" Kurser
Kurser "1..*"--"1..*" Undervisningsafdeling

Database "1"-left-"0..*" Login
Lektioner "0..*"--"1" Kurser
Lektioner "0..*"--"1..*" Ansatte
Skema "1"--"1..*" Undervisere
TA"0..*"--"1..*"Skema
Ansatte "1"--"0..*"Anmodning_til_slet_lektion
Anmodning_til_slet_lektion"1"--"1"Status_på_Anmodning
Status_på_Anmodning"1"--"1"Godkend_eller_afvis

class Database {
-BestBooking
-Valider login()
}

class Godkend_eller_afvis {
-Validering
}

class Status_på_Anmodning {
-Status
}

class Anmodning_til_slet_lektion {
-Anmodning nr
}

class Kurser {
-Navn
-Varighed
}

class Universiteter {
-Navn; KU, DTU
}

class Undervisningsafdeling {
-Navn; SCIENCE, SUND, DTUSCIENCE
}

class Personer {
-Fornavn
-Efternavn
-Vejnavn
-Vej nr
-Tlf.nr
-Email
-Initialer
-CPR

}

class Ansatte {
-Medarbejder nr
}

class TA {
-Medarbejder nr
-Se ledige lokaler ()
-Book lokale ()
-Se kursusoversigt ()
-Se lokaleoversigt ()
-Se skema for undervisning ()
-Se lokalebookinger ()
-Se undervisnings placering ()
}

class Studerende {
-Studie nr.
-Semester nr.
-Se skema for undervisning ()
-Se undervisnings placering ()
-Afmeld kurser ()
-Tilmeld kurser ()
-Se kursusoversigt()
}

class Sekretære {
-Medarbejder nr
-Publicere skema for undervisere og studerende ()
-Se ledige lokaler ()
-Book lokale ()
-Vælg kurser ()
-Afmeld kurser ()
-Tilmeld kurser ()
-Opret kurser ()
-Se kursusoversigt ()
-Se lokale oversigt ()
-Ændre i kurser ()
-Fjern kurser/lektioner ()
-Se skema for undervisning ()
-Se lokalebookinger ()
-Se undervisnings placering ()
-Se status på anmodninger ()
}

class Undervisere {
-Universiteter
-Medarbejder nr
-Skema
-Se ledige lokaler ()
-Book lokale ()
-Se kursusoversigt ()
-Se lokaleoversigt ()
-Ændre i kurser ()
-Fjern kurser/lektioner ()
-Se skema for undervisning ()
-Se lokalebookinger ()
-Se undervisnings placering ()
-Se status på anmodninger ()
}

class Login {
-Brugernavn
-Kodeord
}

class Lektioner {
-Type
-Starttid
-Lokale
-Universiteter
-Sluttid
}

class Skema {
-Uddannelsesnavn
}
@enduml